steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/estcp-build-smart/cloud-run-source-deploy/estcp-supply-chain-tool:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/estcp-build-smart/cloud-run-source-deploy/estcp-supply-chain-tool:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - estcp-supply-chain-tool
      - --image=us-central1-docker.pkg.dev/estcp-build-smart/cloud-run-source-deploy/estcp-supply-chain-tool:$COMMIT_SHA
      - --region=us-central1
      - --allow-unauthenticated
      - --port=8080
      - --memory=512Mi
      - --project=estcp-build-smart

images:
  - us-central1-docker.pkg.dev/estcp-build-smart/cloud-run-source-deploy/estcp-supply-chain-tool:$COMMIT_SHA
